import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteShell, StatusBadge } from "@/components/site-shell";
import { useT } from "@/lib/i18n";
import { useContent } from "@/lib/content";

export const Route = createFileRoute("/claims")({ head: () => ({ meta: [{title:"Claimregister — De Marktplaats van de Ziel"},{name:"description",content:"Alle centrale claims uit de Hexalogie, met bewijsstatus en bronverwijzingen."},{property:"og:title",content:"Claimregister — De Marktplaats van de Ziel"},{property:"og:description",content:"Bekijk wat onderbouwd, betwist, gesteld of onbevestigd is."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}] }), component: ClaimsPage });

function ClaimsPage(){
  const t = useT();
  const { claims } = useContent();
  return <SiteShell><main className="page-wrap"><header className="page-intro"><p className="content-kind kind-onderzoek">{t("Onderzoek · transparantieregister","Research · transparency register")}</p><h1>{t("Wat weten we — en hoe zeker?","What do we know — and how certain is it?")}</h1><p>{t("Geen voetnoten als versiering. Iedere centrale bewering krijgt een eigen ID, status en herleidbare bronnen.","No footnotes as decoration. Every central assertion receives its own ID, status and traceable sources.")}</p></header><div className="claim-table"><div className="claim-head"><span>ID</span><span>{t("Beoordeling","Assessment")}</span><span>{t("Bewering","Assertion")}</span><span>{t("Bronnen","Sources")}</span></div>{claims.map(c=><article className="claim-row" key={c.id}><code>{c.id}</code><StatusBadge status={c.status}/><div><h2>{c.title}</h2><Link to="/onderzoek">{t("Plaats in de Hexalogie →","Place in the Hexalogy →")}</Link></div><p>{c.sources.length ? c.sources.join(" · ") : t("Geen bevestigende bron","No confirming source")}</p></article>)}</div><aside className="editorial-note"><strong>{t("Status is geen waarheidsscore.","Status is not a truth score.")}</strong><span>{t("Een label beschrijft de kwaliteit van het beschikbare bewijs op de versiedatum. Nieuwe informatie kan de beoordeling wijzigen.","A label describes the quality of the available evidence on the version date. New information may change the assessment.")}</span></aside></main></SiteShell>}
