import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, BookOpen, Library } from "lucide-react";
import glassDossier from "@/assets/glass-dossier.jpg";

import { SiteShell, StatusBadge } from "@/components/site-shell";
import { useT } from "@/lib/i18n";
import { useContent } from "@/lib/content";

export const Route = createFileRoute("/")({head:()=>({meta:[{title:"De Marktplaats van de Ziel — Onderzoeksportaal"},{name:"description",content:"Een forensische Hexalogie over de commerciële infrastructuur van digitale intimiteit."},{property:"og:title",content:"De Marktplaats van de Ziel"},{property:"og:description",content:"Zes onderzoekspijlers en één centrale bibliotheek voor controle, beleid en herstel."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HomePage});

function HomePage(){
  const t = useT();
  const { claims } = useContent();
  return <SiteShell><main>
  <section className="manifest-hero"><img src={glassDossier} alt={t("Glazen archieflagen als beeld voor verborgen digitale infrastructuur","Layers of glass archive panels as an image of hidden digital infrastructure")}/><div className="manifest-image-shade"/><div className="manifest-copy"><p className="edition-line"><span>{t("Hexalogie","Hexalogy")}</span><span>{t("Systeemanalyse","Systems analysis")}</span><span>Record · 2026</span></p><h1>{t("De Marktplaats","The Marketplace")}<br/>{t("van de ","of the ")}<em>{t("Ziel","Soul")}</em></h1><p className="manifest-subtitle">{t("Zes boeken · één forensisch onderzoek","Six books · one forensic investigation")}</p><blockquote>{t("“Wie spreekt, wie stuurt en wie verdient wanneer intimiteit infrastructuur wordt?”","“Who speaks, who steers and who profits when intimacy becomes infrastructure?”")}</blockquote><div className="hero-actions"><Link to="/onderzoek" className="primary-action"><BookOpen/>{t("Open het onderzoek","Open the research")}</Link><Link to="/archief" className="secondary-action">{t("Naar de Bibliotheek","Go to the Library")} <ArrowRight/></Link></div></div><a href="#inleiding" className="scroll-cue"><ArrowDown/>{t("Lees verder","Read on")}</a></section>
  <section id="inleiding" className="manifest-intro"><div><p className="eyebrow text-alert">{t("Het kernonderzoek","The core investigation")}</p><h2>{t("Een persoonlijke interface kan een industriële achterkant hebben.","A personal interface can have an industrial back end.")}</h2></div><div><p>{t("De Hexalogie onderzoekt de technische, financiële, psychologische, sociologische en juridische architectuur achter betaalde digitale intimiteit — en de routes naar herstel.","The Hexalogy examines the technical, financial, psychological, sociological and legal architecture behind paid digital intimacy — and the routes to recovery.")}</p><dl><div><dt>06</dt><dd>{t("onderzoeksboeken","research books")}</dd></div><div><dt>01</dt><dd>{t("pers-whitepaper","press white paper")}</dd></div><div><dt>01</dt><dd>{t("centrale bibliotheek","central library")}</dd></div></dl></div></section>
  <section className="three-doors"><header><p className="eyebrow">{t("Drie duidelijke routes","Three clear routes")}</p><h2>{t("Onderzoek, publicaties en wetgeving zonder doublures.","Research, publications and legislation without duplication.")}</h2></header><div><Link to="/onderzoek"><code>01 · {t("INHOUD","CONTENTS")}</code><h3>{t("De zes pijlers","The six pillars")}</h3><p>{t("Van CRM en carding tot neurobiologie, demografie, recht en herstel.","From CRM and carding to neurobiology, demography, law and recovery.")}</p><ArrowRight/></Link><Link to="/archief"><code>02 · {t("PUBLICATIES","PUBLICATIONS")}</code><h3>{t("De Bibliotheek","The Library")}</h3><p>{t("De enige downloadplek voor de zes boeken en de pers-whitepaper.","The only download location for the six books and the press white paper.")}</p><ArrowRight/></Link><Link to="/juridisch"><code>03 · {t("KADER","FRAMEWORK")}</code><h3>Lex Humanitas Digitalis</h3><p>{t("Bestaand recht en een toetsbaar model voor identiteitstransparantie.","Existing law and a testable model for identity transparency.")}</p><ArrowRight/></Link></div></section>
  <section className="claim-ledger"><div><p className="eyebrow text-alert">{t("Bewijs boven bewering","Evidence over assertion")}</p><h2>{t("Iedere centrale claim draagt haar eigen gewicht.","Every central claim carries its own weight.")}</h2><Link to="/claims" className="text-link">{t("Bekijk het volledige register","View the full register")} <ArrowRight/></Link></div><div>{claims.slice(0,4).map(c=><article key={c.id}><div><code>{c.id}</code><StatusBadge status={c.status}/></div><h3>{c.title}</h3><p>{c.sources.length?t(`${c.sources.length} gekoppelde bron${c.sources.length>1?'nen':''}`,`${c.sources.length} linked source${c.sources.length>1?'s':''}`):t("Geen bevestigende bron","No confirming source")}</p></article>)}</div></section>
  <section className="publication-band"><div><p className="eyebrow">{t("Definitieve reeks · 2026","Definitive series · 2026")}</p><h2>{t("Eén gecontroleerde plek voor alle publicaties.","One verified place for every publication.")}</h2><p>{t("De Bibliotheek bevat Boek I–VI, de pers-whitepaper en de integrale uitgaven, met actuele metadata en vaste PDF-uitgaven.","The Library holds Books I–VI, the press white paper and the complete editions, with current metadata and fixed PDF releases.")}</p></div><div className="publication-actions"><Link to="/archief" className="primary-action"><Library/> {t("Open de Bibliotheek","Open the Library")} <ArrowRight/></Link></div></section>
  </main></SiteShell>}
