import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { EditorialPage, SectionLabel } from "@/components/editorial-page";
import { useT } from "@/lib/i18n";

export const Route = createFileRoute("/juridisch/")({head:()=>({meta:[{title:"Juridisch kader — De Marktplaats van de Ziel"},{name:"description",content:"Bestaande Europese kaders en zorgvuldig afgebakende voorstellen rond digitale intimiteit."},{property:"og:title",content:"Juridisch kader — De Marktplaats van de Ziel"},{property:"og:description",content:"Van consumentenrecht en privacy naar toetsbare beleidsvoorstellen."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary"}]}),component:LegalPage});

function LegalPage(){
  const t = useT();
  return <EditorialPage kind="Voorstel" title={t("Recht begint bij wat aantoonbaar is","Law begins with what can be demonstrated")} deck={t("Bestaande regels bieden aanknopingspunten. Nieuwe voorstellen moeten hun noodzaak, werking en neveneffecten nog bewijzen.","Existing rules offer points of departure. New proposals still have to prove their necessity, effect and side effects.")} next={{to:"/onderzoek",label:t("Terug naar de zes onderzoekspijlers","Back to the six research pillars")}}><aside className="evidence-note proposal-note"><strong>{t("Juridische status","Legal status")}</strong><p>{t("Dit is algemene onderzoeksinformatie, geen individueel juridisch advies. Lex Humanitas Digitalis is een modelvoorstel en geen geldend recht.","This is general research information, not individual legal advice. Lex Humanitas Digitalis is a model proposal, not law in force.")}</p></aside><section><SectionLabel>{t("Huidige kaders","Current frameworks")}</SectionLabel><div className="legal-table" role="table" aria-label={t("Huidige juridische kaders","Current legal frameworks")}><div role="row"><strong>{t("Consumentenrecht","Consumer law")}</strong><p>{t("De presentatie van een dienst mag geen essentiële informatie verhullen wanneer die informatie een aankoopbesluit kan beïnvloeden.","The presentation of a service may not conceal essential information where that information can influence a purchasing decision.")}</p></div><div role="row"><strong>{t("Gegevensbescherming","Data protection")}</strong><p>{t("Herleidbare gespreksnotities en profilering kunnen transparantie, doelbinding, minimale verwerking en een geldige grondslag vereisen.","Identifiable conversation notes and profiling can require transparency, purpose limitation, data minimisation and a valid legal basis.")}</p></div><div role="row"><strong>{t("Platformverantwoordelijkheid","Platform responsibility")}</strong><p>{t("De Digital Services Act bevat zorgvuldigheids- en transparantieplichten, maar bepaalt aansprakelijkheid niet zonder beoordeling van concrete feiten.","The Digital Services Act contains due-diligence and transparency obligations, but does not determine liability without an assessment of concrete facts.")}</p></div></div></section><Link className="policy-link" to="/juridisch/lex-humanitas"><span><small>{t("Modelvoorstel","Model proposal")}</small>Lex Humanitas Digitalis</span><ArrowRight/></Link></EditorialPage>}
