import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteShell } from "@/components/site-shell";
import { useLang, useT } from "@/lib/i18n";

export const Route = createFileRoute("/methodologie")({head:()=>({meta:[{title:"Methodologie en correcties — De Marktplaats van de Ziel"},{name:"description",content:"Lees hoe bronnen en claims in het onderzoek zijn geselecteerd, gewogen en gecorrigeerd."},{property:"og:title",content:"Methodologie — De Marktplaats van de Ziel"},{property:"og:description",content:"De bewijsregels, beperkingen en het correctiebeleid van het onderzoek."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary"}]}),component:MethodPage});

const items=[['01','Afbakening','We onderzoeken commerciële infrastructuur: uitbesteed chatwerk, automatisering, profilering, contractuele afhankelijkheid en relevante Europese kaders.'],['02','Bronhiërarchie','Officiële documenten en primair onderzoek wegen zwaarder dan marketingclaims of losse getuigenissen. Productpagina’s gelden alleen als bewijs van aangeboden functionaliteit.'],['03','Claimbeoordeling','Een claim is pas Onderbouwd bij onafhankelijke, relevante bevestiging. Aantijgingen blijven als zodanig herkenbaar. Ontbrekend bewijs wordt niet opgevuld met aannames.'],['04','Wederhoor','De huidige record-versie bevat alleen publiek beschikbaar weerwoord. Gericht wederhoor aan betrokken platforms en bureaus blijft een open redactiestap.'],['05','Correcties','Feitelijke correcties worden in de online versie verwerkt. De datum en reden horen in een openbaar wijzigingslog; stille inhoudelijke wijzigingen zijn niet toegestaan.']];
const itemsEn=[['01','Scope','We examine commercial infrastructure: outsourced chat work, automation, profiling, contractual dependency and the relevant European frameworks.'],['02','Source hierarchy','Official documents and primary research carry more weight than marketing claims or isolated testimonies. Product pages count only as evidence of offered functionality.'],['03','Claim assessment','A claim is only Substantiated with independent, relevant confirmation. Allegations remain recognisable as such. Missing evidence is not filled in with assumptions.'],['04','Right of reply','The current record version contains only publicly available responses. Targeted requests for comment to the platforms and agencies involved remain an open editorial step.'],['05','Corrections','Factual corrections are incorporated into the online version. The date and reason belong in a public change log; silent substantive changes are not permitted.']];

function MethodPage(){
  const t = useT();
  const { lang } = useLang();
  return <SiteShell><main className="page-wrap"><header className="page-intro"><p className="content-kind kind-archief">{t("Archief · verantwoording","Archive · accountability")}</p><h1>{t("Wantrouwen is geen methode.","Distrust is not a method.")}</h1><p>{t("Dit onderzoek maakt scherpe vragen mogelijk door de grens tussen vaststelling, getuigenis en hypothese zichtbaar te houden.","This research enables sharp questions by keeping the boundary between finding, testimony and hypothesis visible.")}</p></header><div className="method-grid">{(lang==="en"?itemsEn:items).map(i=><section key={i[0]}><code>{i[0]}</code><h2>{i[1]}</h2><p>{i[2]}</p></section>)}</div><aside className="editorial-note"><strong>{t("Belangrijke beperking","Important limitation")}</strong><span>{t("Er zijn geen interne datasets, contractarchieven of platformaudits verkregen. De uitgave doet daarom geen representatieve uitspraken over de hele sector.","No internal datasets, contract archives or platform audits were obtained. The publication therefore makes no representative statements about the sector as a whole.")}</span></aside><div className="next-link"><Link to="/claims">{t("Bekijk het claimregister","View the claims register")} <span>→</span></Link></div></main></SiteShell>}
